on:
  workflow_dispatch:
    types: [ created ]
  push:
    branches:
      - main

name: Dev deployment

jobs:
  deploy:
    name: Build image and push to Amazon ECR
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build image
      run: |
        docker build -t kilt-verifier-example:latest .

    - name: Tag, and push image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: verifier-example
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker tag kilt-verifier-example $REGISTRY/$REPOSITORY:latest
        docker tag kilt-verifier-example $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:latest

